language: python

services:
  - docker

branches:
  only:
    - master

install:
  - docker build -t osp:latest .

script:
  - "echo No tests for now"
 
deploy:
  - provider: script
    script: scripts/run_container.sh
    on:
      branches:
        only:
          - master
